package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Thu Nov 06 11:51:29 PST 2014
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1415303489202L;
    public static final String CHECKSUM = "92b4bd16f181a257822f55b6e71a51e5";
    public static final String BARRISTER_VERSION = "0.1.6";
    public static final String PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";
    public static final String NS_PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";

}

