package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Fri Nov 14 18:46:00 PST 2014
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1416019559902L;
    public static final String CHECKSUM = "38ffbd2d5363017f22b1b33b193b6fb4";
    public static final String BARRISTER_VERSION = "0.1.6";
    public static final String PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";
    public static final String NS_PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";

}

