package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Tue Nov 25 17:07:12 PST 2014
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1416964031985L;
    public static final String CHECKSUM = "7bb13f414180b5a05675bf3ed78d2ded";
    public static final String BARRISTER_VERSION = "0.1.6";
    public static final String PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";
    public static final String NS_PACKAGE_NAME="org.sparkbit.jsonrpc.autogen";

}

