package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Nov 16 10:47:14 PST 2014
 */

public interface sparkbit {

    public Boolean createwallet(String walletname) throws com.bitmechanic.barrister.RpcException;
    public String sendasset(String walletname, String address, String assetref, Double quantity, Boolean senderpays) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCStatusResponse getstatus() throws com.bitmechanic.barrister.RpcException;
    public String[] listwallets() throws com.bitmechanic.barrister.RpcException;
    public Boolean deletewallet(String walletname) throws com.bitmechanic.barrister.RpcException;
    public Boolean setassetvisible(String walletname, String assetref, Boolean visibility) throws com.bitmechanic.barrister.RpcException;
    public Boolean addasset(String walletname, String assetref) throws com.bitmechanic.barrister.RpcException;
    public Boolean refreshasset(String walletname, String assetref) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCAddressBookEntry[] listaddresses(String walletname) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCAddressBookEntry[] createaddress(String walletname, Long quantity) throws com.bitmechanic.barrister.RpcException;
    public Boolean setaddresslabel(String walletname, String address, String label) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCTransaction[] listtransactions(String walletname, Long limit) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCBalance[] listbalances(String walletname, Boolean onlyvisible) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoin(String walletname, String address, Double amount) throws com.bitmechanic.barrister.RpcException;

}

