package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sat Oct 25 12:48:12 PDT 2014
 */

public interface SparkBitJSONRPCService {

    public StatusResponse getstatus() throws com.bitmechanic.barrister.RpcException;
    public ListWalletsResponse listwallets() throws com.bitmechanic.barrister.RpcException;

}

