package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Wed Feb 11 15:28:18 PST 2015
 */

public interface sparkbit {

    public Boolean createwallet(String walletname) throws com.bitmechanic.barrister.RpcException;
    public String sendasset(String walletname, String address, String assetref, Double quantity, Boolean senderpays) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCStatusResponse getstatus() throws com.bitmechanic.barrister.RpcException;
    public String[] listwallets() throws com.bitmechanic.barrister.RpcException;
    public Boolean deleteasset(String walletname, String assetref) throws com.bitmechanic.barrister.RpcException;
    public Boolean deletewallet(String walletname) throws com.bitmechanic.barrister.RpcException;
    public Boolean setassetvisible(String walletname, String assetref, Boolean visibility) throws com.bitmechanic.barrister.RpcException;
    public Boolean addasset(String walletname, String assetref) throws com.bitmechanic.barrister.RpcException;
    public Boolean refreshasset(String walletname, String assetref) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCAddressBookEntry[] listaddresses(String walletname) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCAddressBookEntry[] createaddresses(String walletname, Long quantity) throws com.bitmechanic.barrister.RpcException;
    public Boolean setaddresslabel(String walletname, String address, String label) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCTransaction[] listtransactions(String walletname, Long limit) throws com.bitmechanic.barrister.RpcException;
    public JSONRPCBalance[] listbalances(String walletname, Boolean onlyvisible) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoin(String walletname, String address, Double amount) throws com.bitmechanic.barrister.RpcException;
    public Boolean stop() throws com.bitmechanic.barrister.RpcException;
    public JSONRPCUnspentTransactionOutput[] listunspent(String walletname, Long minconf, Long maxconf, String[] addresses) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoinwith(String walletname, String txid, Long vout, String address, Double amount) throws com.bitmechanic.barrister.RpcException;
    public String sendassetwith(String walletname, String txid, Long vout, String address, String assetref, Double quantity, Boolean senderpays) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoinasset(String walletname, String address, Double btc_amount, String assetref, Double asset_qty, Boolean senderpays) throws com.bitmechanic.barrister.RpcException;
    public String sendassetmessage(String walletname, String address, String assetref, Double quantity, Boolean senderpays, String message) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoinmessage(String walletname, String address, Double amount, String message) throws com.bitmechanic.barrister.RpcException;
    public String sendbitcoinassetmessage(String walletname, String address, Double btc_amount, String assetref, Double asset_qty, Boolean senderpays, String message) throws com.bitmechanic.barrister.RpcException;

}

