package org.sparkbit.jsonrpc.autogen;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Fri Nov 07 17:28:18 PST 2014
 */
public class SparkBitJSONRPCServiceClient implements SparkBitJSONRPCService {

    private com.bitmechanic.barrister.Transport _trans;

    public SparkBitJSONRPCServiceClient(com.bitmechanic.barrister.Transport trans) {
        trans.getContract().setPackage("org.sparkbit.jsonrpc.autogen");
        trans.getContract().setNsPackage("org.sparkbit.jsonrpc.autogen");
        this._trans = trans;
    }

    public StatusResponse getstatus() throws com.bitmechanic.barrister.RpcException {
        Object _params = null;
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.getstatus", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (StatusResponse)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public ListWalletsResponse listwallets() throws com.bitmechanic.barrister.RpcException {
        Object _params = null;
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.listwallets", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (ListWalletsResponse)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean deletewallet(String walletID) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.deletewallet", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean createwallet(String description) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { description };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.createwallet", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean setassetvisible(String walletID, String assetRef, Boolean visibility) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, assetRef, visibility };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.setassetvisible", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean addasset(String walletID, String assetRef) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, assetRef };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.addasset", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean refreshasset(String walletID, String assetRef) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, assetRef };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.refreshasset", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public AddressBookEntry[] listaddresses(String walletID) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.listaddresses", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (AddressBookEntry[])_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public AddressBookEntry[] createaddress(String walletID, Long quantity) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, quantity };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.createaddress", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (AddressBookEntry[])_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean setaddresslabel(String walletID, String address, String label) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, address, label };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.setaddresslabel", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public AssetBalance[] listbalances(String walletID, Boolean onlyvisible) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, onlyvisible };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.listbalances", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (AssetBalance[])_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Boolean sendbitcoin(String walletID, String address, Double amount) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, address, amount };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.sendbitcoin", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Boolean)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public AssetTransaction[] listtransactions(String walletID, Long limit) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { walletID, limit };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "SparkBitJSONRPCService.listtransactions", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (AssetTransaction[])_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

}

